"""VenueProfilePackage end-to-end builder.

Composes the 7 minimal subobjects from rubric v2 §1:
  1. VenueIdentity (from input identity dict)
  2. VenueFieldPosition (from corpus_hull_builder)
  3. PublishedCorpusHull (from venue_corpus_miner)
  4. EditorialBoardCloud (from editorial_board adapter, optional)
  5. FormalSubmissionProfile (deferred — left as `partial` unless caller
                              supplies a publication_regime_id)
  6. CitationExpectationProfile (derived from corpus references; lite)
  7. SourceEvidencePacket (autogenerated)

Then persists to the venue_profile_registry by identity.

NO LLM. NO new architecture beyond what's already added. Each subobject
is honestly marked `present | missing | partial` in `completeness`.
"""

from __future__ import annotations

import logging
from typing import Any

from ..schema import (
    CitationExpectationProfile,
    SourceEvidencePacket,
    VenueProfilePackage,
)
from ..adapters.venue.editorial_board import build_editorial_board_cloud
from .venue_corpus_miner import mine_venue_corpus
from .venue_profile_registry import VenueProfileRegistry

logger = logging.getLogger(__name__)


def _completeness(present: bool, partial: bool = False) -> str:
    if present:
        return "present"
    if partial:
        return "partial"
    return "missing"


def build_venue_profile_package(
    *,
    identity: dict[str, Any],
    fetch_corpus: bool = True,
    fetch_editorial_board: bool = False,
    max_works: int = 30,
    board_page_url: str | None = None,
    registry: VenueProfileRegistry | None = None,
) -> VenueProfilePackage:
    """Build (or refresh) a VenueProfilePackage from real sources.

    identity must carry at least one of:
      - `canonical_name`
      - `issns`
      - `openalex_source_id`

    fetch_corpus: if True and openalex_source_id is set, mines real
    OpenAlex Works → corpus → hull (subobject 2 + 3).

    fetch_editorial_board: if True and board_page_url is set, builds
    EditorialBoardCloud (subobject 4).

    If a registry is supplied, the resulting package is `upsert`ed and
    the returned object is the merged version.
    """
    vpkg = VenueProfilePackage(
        canonical_name=identity.get("canonical_name"),
        issns=list(identity.get("issns") or []),
        publisher=identity.get("publisher"),
        homepage_url=identity.get("homepage_url"),
        languages=list(identity.get("languages") or []),
        venue_type=identity.get("venue_type", "journal"),
        openalex_source_id=identity.get("openalex_source_id"),
        doaj_source_id=identity.get("doaj_source_id"),
        crossref_member_id=identity.get("crossref_member_id"),
        cyberleninka_source_id=identity.get("cyberleninka_source_id"),
        discovery_sources=list(identity.get("discovery_sources") or []),
        discovery_clusters=list(identity.get("discovery_clusters") or []),
    )

    # Subobject 1: VenueIdentity — implicit from the above; mark complete
    # if we have at least name OR an ISSN.
    has_identity = bool(vpkg.canonical_name or vpkg.issns)
    vpkg.completeness["VenueIdentity"] = _completeness(has_identity)
    if not has_identity:
        vpkg.warnings.append(
            "no canonical_name, no ISSN — identity is empty; "
            "registry upsert will create an orphan record"
        )

    # Subobjects 2 + 3: PublishedCorpusHull (and the FPM it composes)
    corpus_hull = None
    venue_fpm = None
    if fetch_corpus and vpkg.openalex_source_id:
        logger.info("Mining corpus for %s (OpenAlex %s)",
                    vpkg.canonical_name, vpkg.openalex_source_id)
        try:
            venue_fpm, corpus_hull = mine_venue_corpus(
                vpkg.openalex_source_id,
                venue_model_id=None,
                max_works=max_works,
            )
            vpkg.venue_field_position_id = venue_fpm.field_position_id
            vpkg.published_corpus_hull_id = corpus_hull.published_corpus_hull_id
            corpus_present = corpus_hull.works_fetched > 0
            vpkg.completeness["PublishedCorpusHull"] = _completeness(
                corpus_present, partial=(corpus_hull.abstracts_available == 0
                                          and corpus_present),
            )
            vpkg.completeness["VenueFieldPosition"] = _completeness(corpus_present)
        except Exception as exc:  # noqa: BLE001
            logger.warning("corpus mining failed for %s: %s",
                           vpkg.canonical_name, exc)
            vpkg.warnings.append(f"corpus mining failed: {exc}")
            vpkg.completeness["PublishedCorpusHull"] = "missing"
            vpkg.completeness["VenueFieldPosition"] = "missing"
    else:
        vpkg.completeness["PublishedCorpusHull"] = "missing"
        vpkg.completeness["VenueFieldPosition"] = "missing"
        if fetch_corpus and not vpkg.openalex_source_id:
            vpkg.unknowns.append(
                "no openalex_source_id — corpus mining skipped"
            )

    # Subobject 4: EditorialBoardCloud
    board_cloud = None
    if fetch_editorial_board and board_page_url:
        logger.info("Building editorial board cloud from %s", board_page_url)
        try:
            board_cloud = build_editorial_board_cloud(
                board_page_url=board_page_url,
                venue_profile_package_id=vpkg.venue_profile_package_id,
                target_sample=30,
            )
            vpkg.editorial_board_cloud_id = board_cloud.editorial_board_cloud_id
            present = board_cloud.members_sampled > 0
            vpkg.completeness["EditorialBoardCloud"] = _completeness(
                present, partial=(present and board_cloud.members_sampled < 6),
            )
            if board_cloud.warnings:
                vpkg.warnings.extend(board_cloud.warnings)
            if board_cloud.unknowns:
                vpkg.unknowns.extend(board_cloud.unknowns)
        except Exception as exc:  # noqa: BLE001
            logger.warning("editorial board build failed: %s", exc)
            vpkg.warnings.append(f"editorial board build failed: {exc}")
            vpkg.completeness["EditorialBoardCloud"] = "missing"
    else:
        vpkg.completeness["EditorialBoardCloud"] = "missing"

    # Subobject 5: FormalSubmissionProfile — deferred at this layer
    vpkg.completeness["FormalSubmissionProfile"] = "missing"
    vpkg.unknowns.append(
        "FormalSubmissionProfile not built: needs author guidelines "
        "extraction (deferred — separate sprint)"
    )

    # Subobject 6: CitationExpectationProfile — lite version from corpus
    if corpus_hull and corpus_hull.references_available > 0:
        cep = CitationExpectationProfile(
            venue_model_id=None,
            typical_reference_count=str(
                round(corpus_hull.corpus_analysis_summary.get("corpus_size", 0))
            ),
            confidence="low",
            unknowns=[
                "must_cite list requires per-article references parsing — "
                "OpenAlex referenced_works IDs available but author/title "
                "expansion needs an extra call per work (deferred for "
                "rate-limit reasons)"
            ],
        )
        vpkg.citation_expectation_profile_id = cep.citation_expectation_profile_id
        vpkg.completeness["CitationExpectationProfile"] = "partial"
    else:
        vpkg.completeness["CitationExpectationProfile"] = "missing"

    # Subobject 7: SourceEvidencePacket (lite)
    sep_entries = []
    for src in vpkg.discovery_sources:
        sep_entries.append({
            "source_id": f"{src}:{vpkg.canonical_name or 'unknown'}",
            "source_type": src,
            "provenance": "web_source" if src in ("DOAJ", "OpenAlex", "Crossref", "CyberLeninka") else "user_statement",
            "access_status": "full",
            "extraction_status": "parsed",
            "granularity": "vendor_claim",
        })
    sep = SourceEvidencePacket(
        case_id=None,
        input_sources=sep_entries,
        granularity_summary={"vendor_claim": len(sep_entries)},
    )
    vpkg.source_evidence_packet_id = sep.source_evidence_packet_id
    vpkg.completeness["SourceEvidencePacket"] = "present"

    # Overall confidence
    present_count = sum(1 for v in vpkg.completeness.values() if v == "present")
    partial_count = sum(1 for v in vpkg.completeness.values() if v == "partial")
    if present_count >= 5:
        vpkg.confidence = "high"
    elif present_count + partial_count >= 4:
        vpkg.confidence = "medium"
    else:
        vpkg.confidence = "low"

    # Persist
    if registry is not None:
        vpkg = registry.upsert(vpkg)

    return vpkg
