"""One-shot seeder for international disciplines. Run from repo root."""
import json
from pathlib import Path

seeds = [
    {
        "discipline_id": "intl-sts",
        "display_names": {"en": "Science and Technology Studies", "ru": "Исследования науки и технологий"},
        "aliases": ["STS", "science studies", "social studies of science"],
        "paradigm": "Science and technology as social, material, and political practices. Symmetry between human and nonhuman actors. Co-production of knowledge and order.",
        "epistemic_regime": "Empirical-interpretive: ethnographies of laboratories, historical reconstruction of controversies, network mapping. Knowledge as situated.",
        "forms_of_evidence": ["laboratory ethnography", "controversy mapping", "historical case study", "interview", "document analysis"],
        "canonical_questions": ["How is scientific fact produced?", "How do technologies acquire social trajectories?", "Who counts as a legitimate knower?"],
        "typical_problem_forms": ["black-boxing of contested practice", "asymmetric attribution to humans/nonhumans", "co-production puzzle"],
        "legitimate_objects": ["laboratory", "scientific controversy", "sociotechnical system", "expertise", "infrastructure", "standard"],
        "illegitimate_or_borderline_objects": ["pure philosophy of science (normative epistemology)", "engineering optimization"],
        "argument_styles": ["empirical case study", "controversy reconstruction", "comparative ethnography", "symmetrical description"],
        "publication_genres": ["empirical research article", "theoretical essay", "book chapter", "review essay"],
        "institutional_forms": ["STS programs", "4S society", "EASST", "Science Studies departments"],
        "international_mapping": ["ru-philosophy-of-technology"],
        "methods": ["ethnography", "discourse analysis", "actor-network analysis", "historical reconstruction"],
        "instruments": ["ANT", "SCOT", "co-production framework"],
        "ontologies": ["actor-network", "assemblage", "boundary object", "epistemic culture"],
        "key_authors": [
            {"name": "Bruno Latour", "role": "founder", "era": "20th–21st c.", "discipline_relevance": "ANT founder."},
            {"name": "Sheila Jasanoff", "role": "contemporary", "era": None, "discipline_relevance": "Co-production framework."},
            {"name": "Donna Haraway", "role": "classic", "era": None, "discipline_relevance": "Situated knowledges."},
        ],
        "history": "Emerges 1970s from sociology of science (Bloor, Edinburgh) and history of science. Latour 1979 (Laboratory Life) inaugurates lab-ethnographic turn.",
        "boundaries": "Distinct from philosophy of science (normative, conceptual) and from history of science (purely historical). STS is empirical AND theoretical.",
        "adjacent": ["intl-philosophy-of-technology", "intl-actor-network-theory", "intl-digital-humanities"],
    },
    {
        "discipline_id": "intl-philosophy-of-mind",
        "display_names": {"en": "Philosophy of mind", "ru": "Философия сознания"},
        "aliases": ["phil mind"],
        "paradigm": "Nature of mental states, consciousness, intentionality, and their relation to physical substrate.",
        "epistemic_regime": "Conceptual analysis, thought experiment, integration with empirical cognitive science.",
        "forms_of_evidence": ["thought experiment", "conceptual analysis", "empirical findings from cognitive science as constraints", "introspective reports"],
        "canonical_questions": ["What is consciousness?", "Is the mind reducible to the physical?", "Can a machine think?"],
        "typical_problem_forms": ["explanatory gap", "hard problem of consciousness", "intentionality puzzle"],
        "legitimate_objects": ["consciousness", "intentionality", "qualia", "mental representation", "personal identity"],
        "illegitimate_or_borderline_objects": ["empirical neuroscience data without philosophical framing", "psychiatric pathology classification"],
        "argument_styles": ["conceptual analysis", "thought experiment", "reductio", "transcendental argument"],
        "publication_genres": ["theoretical essay", "philosophical commentary", "book chapter", "polemical article"],
        "institutional_forms": ["philosophy departments", "cognitive science programs", "ASSC"],
        "international_mapping": [],
        "methods": ["conceptual analysis", "thought experiment", "phenomenological reflection"],
        "instruments": ["zombie argument", "Mary's room", "Chinese room", "inverted spectrum"],
        "ontologies": ["physicalism", "dualism", "functionalism", "panpsychism", "illusionism"],
        "key_authors": [
            {"name": "David Chalmers", "role": "contemporary", "era": None, "discipline_relevance": "Hard problem of consciousness."},
            {"name": "Daniel Dennett", "role": "contemporary", "era": None, "discipline_relevance": "Intentional stance, illusionism."},
        ],
        "history": "Modern philosophy of mind crystallizes post-1950 with rise of cognitive science. Functionalism dominant 1960s-80s; consciousness studies revival 1990s.",
        "boundaries": "Distinct from psychology (empirical) and from cognitive neuroscience (mechanistic).",
        "adjacent": ["intl-philosophy-of-ai", "intl-cognitive-science", "intl-epistemology"],
    },
    {
        "discipline_id": "intl-philosophy-of-science",
        "display_names": {"en": "Philosophy of science", "ru": "Философия науки"},
        "aliases": ["phil sci"],
        "paradigm": "Structure, methods, and aims of science. Theory change, explanation, scientific realism, demarcation.",
        "epistemic_regime": "Conceptual analysis + reconstruction of scientific practice. Historical case studies as test cases for philosophical claims.",
        "forms_of_evidence": ["historical case study", "conceptual analysis", "logical reconstruction", "formal modeling"],
        "canonical_questions": ["What distinguishes science from non-science?", "How do scientific theories change?", "Are theoretical entities real?"],
        "typical_problem_forms": ["underdetermination", "theory-ladenness", "demarcation problem", "scientific revolution"],
        "legitimate_objects": ["scientific theory", "explanation", "model", "law", "experiment", "paradigm"],
        "illegitimate_or_borderline_objects": ["pure sociology of scientific institutions (STS territory)"],
        "argument_styles": ["conceptual analysis", "historical reconstruction", "formal logic", "inference to best explanation"],
        "publication_genres": ["theoretical essay", "historical-philosophical study", "book chapter", "systematic review"],
        "institutional_forms": ["philosophy departments", "HPS programs", "PSA"],
        "international_mapping": [],
        "methods": ["conceptual analysis", "historical case study", "formal modeling"],
        "instruments": ["Bayesian framework", "scientific realism debate", "paradigm analysis"],
        "ontologies": ["theory", "model", "paradigm", "research programme", "scientific revolution"],
        "key_authors": [
            {"name": "Karl Popper", "role": "classic", "era": "20th c.", "discipline_relevance": "Falsificationism."},
            {"name": "Thomas Kuhn", "role": "classic", "era": "20th c.", "discipline_relevance": "Paradigm shifts."},
            {"name": "Imre Lakatos", "role": "classic", "era": "20th c.", "discipline_relevance": "Research programmes."},
        ],
        "history": "Logical positivism 1920s-50s. Popper, Kuhn, Lakatos 1960s-70s. Sociological turn 1980s-90s.",
        "boundaries": "Distinct from STS (empirical) and history of science (descriptive).",
        "adjacent": ["intl-epistemology", "intl-sts", "intl-philosophy-of-mind"],
    },
    {
        "discipline_id": "intl-epistemology",
        "display_names": {"en": "Epistemology", "ru": "Эпистемология"},
        "aliases": ["theory of knowledge"],
        "paradigm": "Nature, sources, structure, and limits of knowledge. Justification, truth, belief.",
        "epistemic_regime": "Conceptual analysis, thought experiment, formal methods (Bayesian, modal). Reflective equilibrium between intuitions and theory.",
        "forms_of_evidence": ["conceptual analysis", "thought experiment", "formal proof", "appeal to intuition"],
        "canonical_questions": ["What is knowledge?", "What justifies belief?", "How do we know we know?", "What are the limits of knowledge?"],
        "typical_problem_forms": ["Gettier problem", "skeptical scenarios", "regress of justification"],
        "legitimate_objects": ["knowledge", "belief", "justification", "evidence", "rationality", "testimony"],
        "illegitimate_or_borderline_objects": ["empirical psychology of reasoning (cognitive psychology)", "sociology of knowledge institutions"],
        "argument_styles": ["conceptual analysis", "thought experiment", "transcendental argument", "reductio"],
        "publication_genres": ["theoretical essay", "philosophical commentary", "book chapter", "polemical article"],
        "institutional_forms": ["philosophy departments", "epistemology research groups"],
        "international_mapping": [],
        "methods": ["conceptual analysis", "thought experiment", "formal modeling"],
        "instruments": ["Gettier cases", "skeptical hypothesis", "Bayesian framework", "reliabilist counterfactuals"],
        "ontologies": ["belief", "knowledge", "justification", "truth", "epistemic agent"],
        "key_authors": [
            {"name": "Edmund Gettier", "role": "boundary_setter", "era": "20th c.", "discipline_relevance": "1963 paper shattered classical JTB definition."},
            {"name": "Alvin Goldman", "role": "contemporary", "era": None, "discipline_relevance": "Reliabilism, social epistemology."},
            {"name": "Timothy Williamson", "role": "contemporary", "era": None, "discipline_relevance": "Knowledge-first epistemology."},
        ],
        "history": "Ancient roots (Plato, Aristotle). Modern crisis with Descartes. Gettier 1963 problem reshapes contemporary debate.",
        "boundaries": "Distinct from cognitive psychology (empirical) and philosophy of mind (focus on knowledge specifically).",
        "adjacent": ["intl-philosophy-of-mind", "intl-philosophy-of-science"],
    },
    {
        "discipline_id": "intl-cognitive-science",
        "display_names": {"en": "Cognitive science", "ru": "Когнитивная наука"},
        "aliases": ["cog sci"],
        "paradigm": "Interdisciplinary study of mind, brain, language, computation. Mind as information-processing system.",
        "epistemic_regime": "Triangulation across psychology, neuroscience, linguistics, AI, philosophy. Experimental + computational + theoretical.",
        "forms_of_evidence": ["behavioral experiments", "neuroimaging", "computational modeling", "linguistic data"],
        "canonical_questions": ["How does the mind compute?", "What is the architecture of cognition?", "How are concepts represented?"],
        "typical_problem_forms": ["modularity vs domain-general", "symbolic vs connectionist", "embodied vs computational"],
        "legitimate_objects": ["cognitive architecture", "mental representation", "attention", "memory", "language processing", "reasoning"],
        "illegitimate_or_borderline_objects": ["clinical psychopathology (clinical psychology)", "social institutions of knowledge (sociology)"],
        "argument_styles": ["experimental design", "computational modeling", "convergent evidence integration"],
        "publication_genres": ["empirical research article (IMRAD)", "computational modeling paper", "review article"],
        "institutional_forms": ["cognitive science programs", "psychology departments", "Cognitive Science Society"],
        "international_mapping": [],
        "methods": ["psychophysics", "fMRI", "computational modeling", "behavioral experiments"],
        "instruments": ["ACT-R", "connectionist networks", "Bayesian models", "neuroimaging tools"],
        "ontologies": ["representation", "process", "module", "architecture", "embodiment"],
        "key_authors": [
            {"name": "Marvin Minsky", "role": "founder", "era": "20th c.", "discipline_relevance": "AI/cogsci foundational."},
            {"name": "Jerry Fodor", "role": "classic", "era": "20th c.", "discipline_relevance": "Modularity of mind."},
            {"name": "Andy Clark", "role": "contemporary", "era": None, "discipline_relevance": "Extended mind, predictive processing."},
        ],
        "history": "1956 Dartmouth + Chomsky's review of Skinner inaugurate cognitive revolution. 1980s connectionism. 2000s embodied turn.",
        "boundaries": "Distinct from neuroscience (mechanistic only) and philosophy of mind (conceptual only).",
        "adjacent": ["intl-philosophy-of-mind", "intl-philosophy-of-ai", "intl-natural-language-processing"],
    },
    {
        "discipline_id": "intl-machine-learning",
        "display_names": {"en": "Machine learning", "ru": "Машинное обучение"},
        "aliases": ["ML", "statistical learning"],
        "paradigm": "Algorithms that learn patterns from data. Generalization from samples to unseen instances.",
        "epistemic_regime": "Empirical-engineering: hypotheses tested via benchmark performance. Mathematical proof for theoretical bounds.",
        "forms_of_evidence": ["benchmark performance metrics", "ablation studies", "mathematical proof of bounds", "comparative experiments"],
        "canonical_questions": ["How can a model generalize?", "What is the sample complexity?", "How to optimize objective?"],
        "typical_problem_forms": ["overfitting vs underfitting", "bias-variance tradeoff", "distribution shift", "sample inefficiency"],
        "legitimate_objects": ["learning algorithm", "model class", "loss function", "dataset", "benchmark", "inductive bias"],
        "illegitimate_or_borderline_objects": ["philosophical questions about understanding (philosophy of AI)", "deployment ethics (AI ethics)"],
        "argument_styles": ["empirical benchmarking", "mathematical proof", "ablation analysis"],
        "publication_genres": ["empirical research article (NeurIPS/ICML format)", "technical report", "benchmark paper", "survey"],
        "institutional_forms": ["CS departments", "industry research labs", "NeurIPS/ICML/ICLR community"],
        "international_mapping": [],
        "methods": ["supervised learning", "unsupervised learning", "reinforcement learning", "deep learning"],
        "instruments": ["neural networks", "decision trees", "kernel methods", "Bayesian inference"],
        "ontologies": ["model", "loss", "gradient", "representation", "distribution"],
        "key_authors": [
            {"name": "Geoffrey Hinton", "role": "founder", "era": None, "discipline_relevance": "Deep learning."},
            {"name": "Yann LeCun", "role": "founder", "era": None, "discipline_relevance": "CNNs."},
            {"name": "Vladimir Vapnik", "role": "classic", "era": None, "discipline_relevance": "Statistical learning theory, SVMs."},
        ],
        "history": "Perceptron 1958. AI winters 1970s/80s. Statistical learning theory 1990s. Deep learning revolution 2012 (AlexNet). Transformer era from 2017.",
        "boundaries": "Distinct from statistics (less algorithmic-engineering focus) and from AI broadly (ML is one branch).",
        "adjacent": ["intl-natural-language-processing", "intl-philosophy-of-ai", "intl-ai-ethics"],
    },
    {
        "discipline_id": "intl-natural-language-processing",
        "display_names": {"en": "Natural language processing", "ru": "Компьютерная обработка естественного языка"},
        "aliases": ["NLP", "computational linguistics"],
        "paradigm": "Computational processing of human language. Increasingly LLM-centric in contemporary practice.",
        "epistemic_regime": "Empirical-engineering with linguistic theory as background. Benchmark-driven evaluation.",
        "forms_of_evidence": ["benchmark scores", "human evaluation", "linguistic probing", "ablation studies"],
        "canonical_questions": ["How can machines understand text?", "What linguistic structure do models learn?", "How to evaluate generation quality?"],
        "typical_problem_forms": ["ambiguity resolution", "long-range dependency", "evaluation of open-ended generation", "low-resource languages"],
        "legitimate_objects": ["text", "language model", "token", "embedding", "linguistic structure", "annotated corpus"],
        "illegitimate_or_borderline_objects": ["theoretical syntax without computational angle", "phenomenology of meaning"],
        "argument_styles": ["benchmark comparison", "probing analysis", "linguistic theory application"],
        "publication_genres": ["empirical research article (ACL/EMNLP format)", "survey", "shared-task report"],
        "institutional_forms": ["CS departments", "linguistics departments", "ACL community"],
        "international_mapping": [],
        "methods": ["statistical NLP", "neural NLP", "rule-based parsing", "transfer learning"],
        "instruments": ["transformers", "tokenizers", "annotated corpora", "evaluation benchmarks"],
        "ontologies": ["token", "embedding", "attention", "language model", "annotation"],
        "key_authors": [
            {"name": "Christopher Manning", "role": "contemporary", "era": None, "discipline_relevance": "Statistical NLP, foundation models."},
            {"name": "Yoshua Bengio", "role": "founder", "era": None, "discipline_relevance": "Neural language models."},
        ],
        "history": "Symbolic NLP 1960s-80s. Statistical NLP 1990s-2000s. Neural turn 2013 (word2vec). Transformer revolution 2017. LLM era from 2018.",
        "boundaries": "Distinct from theoretical linguistics (descriptive) and from speech recognition (acoustic).",
        "adjacent": ["intl-machine-learning", "intl-llm-studies", "intl-cognitive-science"],
    },
    {
        "discipline_id": "intl-learning-sciences",
        "display_names": {"en": "Learning sciences", "ru": "Науки об обучении"},
        "aliases": ["LS", "learning research"],
        "paradigm": "Interdisciplinary study of how people learn in real settings. Design-based research as signature method.",
        "epistemic_regime": "Mixed methods. Design experiments in authentic settings; iterative refinement; ecological validity prioritized.",
        "forms_of_evidence": ["design experiments", "classroom ethnography", "learning analytics", "interaction analysis"],
        "canonical_questions": ["How do people learn?", "What instructional designs work?", "How does technology mediate learning?"],
        "typical_problem_forms": ["transfer problem", "scaling of effective designs", "equity of learning outcomes"],
        "legitimate_objects": ["learning environment", "instructional design", "conceptual change", "learning trajectory", "scaffolding"],
        "illegitimate_or_borderline_objects": ["psychometric test design (educational measurement)", "policy analysis (education policy)"],
        "argument_styles": ["design-based research", "longitudinal case study", "comparative intervention study"],
        "publication_genres": ["empirical research article", "design case study", "theoretical commentary"],
        "institutional_forms": ["education schools", "ISLS society", "learning sciences programs"],
        "international_mapping": ["ru-pedagogical-psychology", "ru-developing-learning-theory"],
        "methods": ["design experiments", "interaction analysis", "learning analytics", "ethnography"],
        "instruments": ["video analysis", "trace data tools", "concept maps"],
        "ontologies": ["scaffolding", "zone of proximal development", "conceptual change", "communities of practice"],
        "key_authors": [
            {"name": "Ann Brown", "role": "founder", "era": "20th c.", "discipline_relevance": "Design experiments."},
            {"name": "Jean Lave", "role": "classic", "era": None, "discipline_relevance": "Situated learning."},
            {"name": "Roy Pea", "role": "founder", "era": None, "discipline_relevance": "Distributed cognition, ISLS."},
        ],
        "history": "Field crystallizes 1990s from cognitive science + Vygotskian sociocultural theory + design research.",
        "boundaries": "Distinct from educational psychology (lab-individual) and curriculum studies (program-level).",
        "adjacent": ["intl-ai-in-education", "ru-pedagogical-psychology", "intl-cognitive-science"],
    },
    {
        "discipline_id": "intl-ai-in-education",
        "display_names": {"en": "AI in education", "ru": "ИИ в образовании"},
        "aliases": ["AIED", "AI4Education"],
        "paradigm": "Application of AI techniques to learning, teaching, assessment, and educational systems.",
        "epistemic_regime": "Empirical-engineering: build system, evaluate in classroom, measure learning outcomes.",
        "forms_of_evidence": ["learning outcome experiments", "system evaluation", "log data analysis", "qualitative classroom studies"],
        "canonical_questions": ["How can AI personalize learning?", "What does LLM-assisted learning change?", "How to assess in the age of generative AI?"],
        "typical_problem_forms": ["learning effect vs novelty effect", "academic integrity in LLM era", "algorithmic fairness in education"],
        "legitimate_objects": ["intelligent tutoring system", "learning analytics dashboard", "LLM-based tutor", "adaptive assessment"],
        "illegitimate_or_borderline_objects": ["pure ML benchmarking without educational evaluation", "school administration software"],
        "argument_styles": ["intervention study", "design-based research", "ethical analysis", "case study"],
        "publication_genres": ["empirical research article (AIED/JEDM format)", "system description", "ethical commentary"],
        "institutional_forms": ["AIED society", "education schools", "EdTech research labs"],
        "international_mapping": [],
        "methods": ["randomized intervention", "log analysis", "design-based research", "stakeholder interviews"],
        "instruments": ["intelligent tutors", "learning dashboards", "LLM-tutoring systems"],
        "ontologies": ["learner model", "domain model", "pedagogical model", "adaptive scaffold"],
        "key_authors": [
            {"name": "Ryan Baker", "role": "contemporary", "era": None, "discipline_relevance": "Educational data mining, AIED."},
            {"name": "Kenneth Koedinger", "role": "contemporary", "era": None, "discipline_relevance": "Cognitive tutors."},
        ],
        "history": "Roots in 1970s intelligent tutoring. 1990s ITS revival. 2010s MOOCs + learning analytics. 2022+ LLM transformation.",
        "boundaries": "Distinct from EdTech industry (product-focused) and learning sciences (broader).",
        "adjacent": ["intl-learning-sciences", "intl-ai-ethics", "intl-llm-studies"],
    },
    {
        "discipline_id": "intl-digital-humanities",
        "display_names": {"en": "Digital humanities", "ru": "Цифровые гуманитарные науки"},
        "aliases": ["DH"],
        "paradigm": "Computational methods on humanistic objects (texts, images, archives) AND humanistic reflection on digital culture.",
        "epistemic_regime": "Two-fold: computational analysis of large-scale humanistic data + critical-interpretive reflection on the digital turn.",
        "forms_of_evidence": ["computational corpus analysis", "data visualization", "critical close reading", "infrastructure analysis"],
        "canonical_questions": ["What can computation reveal about humanistic texts?", "How does the digital reshape humanistic objects?"],
        "typical_problem_forms": ["distant vs close reading tension", "data-set construction as interpretive act", "platform dependency"],
        "legitimate_objects": ["digital archive", "text corpus", "computational model of humanistic phenomenon", "digital edition"],
        "illegitimate_or_borderline_objects": ["pure NLP without humanistic question (NLP territory)", "library science workflows"],
        "argument_styles": ["computational analysis", "close reading", "critical commentary"],
        "publication_genres": ["empirical-computational article", "theoretical essay", "tool/method paper", "digital edition"],
        "institutional_forms": ["DH centers", "literature departments", "ADHO", "DH initiatives in libraries"],
        "international_mapping": [],
        "methods": ["text mining", "topic modeling", "network analysis", "critical infrastructure studies"],
        "instruments": ["Voyant", "Gephi", "TEI", "topic models"],
        "ontologies": ["distant reading", "macroanalysis", "digital edition", "cultural analytics"],
        "key_authors": [
            {"name": "Franco Moretti", "role": "boundary_setter", "era": None, "discipline_relevance": "Distant reading."},
            {"name": "Matthew Jockers", "role": "contemporary", "era": None, "discipline_relevance": "Macroanalysis."},
        ],
        "history": "Humanities computing 1940s-90s. Field reframes as DH in 2000s. Computational turn + critical-infrastructural turn coexist 2010s.",
        "boundaries": "Distinct from computational linguistics (technique-focused) and media studies (broader).",
        "adjacent": ["intl-sts", "intl-natural-language-processing", "intl-philosophy-of-technology"],
    },
    {
        "discipline_id": "intl-philosophical-anthropology",
        "display_names": {"en": "Philosophical anthropology", "ru": "Философская антропология"},
        "aliases": ["phil anthro"],
        "paradigm": "Human as philosophical question: unfinished, technical, cultural, world-open creature.",
        "epistemic_regime": "Conceptual reflection on the human informed by biology, anthropology, history.",
        "forms_of_evidence": ["conceptual analysis", "integration of empirical findings", "phenomenological description", "comparative anthropology"],
        "canonical_questions": ["What is the essence of the human?", "What distinguishes human from animal and from machine?"],
        "typical_problem_forms": ["nature/nurture/technique entanglement", "human exceptionalism vs continuity", "post-human prospects"],
        "legitimate_objects": ["human as such", "embodiment", "world-openness", "technicity of the human", "human/animal boundary"],
        "illegitimate_or_borderline_objects": ["cultural anthropology (empirical)", "evolutionary biology (purely empirical)"],
        "argument_styles": ["philosophical reflection", "integration of biological and cultural perspectives"],
        "publication_genres": ["theoretical essay", "monograph", "philosophical commentary"],
        "institutional_forms": ["philosophy departments", "Plessner-tradition centers"],
        "international_mapping": ["ru-philosophy-of-technology"],
        "methods": ["philosophical reflection", "phenomenological description", "comparative analysis"],
        "instruments": ["world-openness concept", "eccentric positionality", "originary technicity"],
        "ontologies": ["world-openness", "embodiment", "eccentric positionality", "technicity"],
        "key_authors": [
            {"name": "Max Scheler", "role": "founder", "era": "20th c.", "discipline_relevance": "Scheler's man's place in the cosmos."},
            {"name": "Helmuth Plessner", "role": "classic", "era": "20th c.", "discipline_relevance": "Eccentric positionality."},
            {"name": "Arnold Gehlen", "role": "classic", "era": "20th c.", "discipline_relevance": "Human as unfinished, technical animal."},
            {"name": "Bernard Stiegler", "role": "contemporary", "era": None, "discipline_relevance": "Originary technicity."},
        ],
        "history": "Modern form crystallizes 1920s-30s (Scheler, Plessner, Gehlen). Postwar marginalization. Revival via Stiegler 2000s.",
        "boundaries": "Distinct from cultural anthropology (empirical) and philosophical biology (narrower).",
        "adjacent": ["intl-philosophy-of-technology", "intl-philosophy-of-mind"],
    },
    {
        "discipline_id": "intl-actor-network-theory",
        "display_names": {"en": "Actor-Network Theory", "ru": "Акторно-сетевая теория"},
        "aliases": ["ANT"],
        "paradigm": "Social and technical reality as networks of human and nonhuman actors. Symmetric treatment.",
        "epistemic_regime": "Empirical-descriptive: follow the actors. Refuse a priori social structure; reconstruct networks from traces.",
        "forms_of_evidence": ["ethnographic following of actors", "network reconstruction", "historical archive of mediations"],
        "canonical_questions": ["What actors compose this network?", "How are translations established and maintained?", "What does the artifact do (its agency)?"],
        "typical_problem_forms": ["asymmetric attribution of agency", "social-structural shortcuts", "missing mediators"],
        "legitimate_objects": ["actor-network", "mediator", "translation", "delegate", "obligatory passage point"],
        "illegitimate_or_borderline_objects": ["pure macro-sociology (Latour critiques it explicitly)"],
        "argument_styles": ["ethnographic description", "symmetric tracing", "controversy reconstruction"],
        "publication_genres": ["empirical case study", "theoretical essay", "book chapter"],
        "institutional_forms": ["STS departments", "Latourian schools", "4S/EASST communities"],
        "international_mapping": [],
        "methods": ["ethnography", "controversy mapping", "network tracing"],
        "instruments": ["translation framework", "obligatory passage point"],
        "ontologies": ["actor-network", "mediator/intermediary distinction", "translation"],
        "key_authors": [
            {"name": "Bruno Latour", "role": "founder", "era": "20th–21st c.", "discipline_relevance": "Founding figure."},
            {"name": "Michel Callon", "role": "founder", "era": None, "discipline_relevance": "Translation framework."},
            {"name": "John Law", "role": "founder", "era": None, "discipline_relevance": "Modes of ordering."},
        ],
        "history": "Emerges 1980s (Callon's scallops 1986, Latour's Science in Action 1987). Latour Reassembling 2005 as methodological manifesto.",
        "boundaries": "ANT is part of STS but methodologically distinct: symmetric, non-structural.",
        "adjacent": ["intl-sts", "intl-philosophy-of-technology", "intl-digital-humanities"],
    },
]

for s in seeds:
    s["schema_version"] = "1.0.0"
    s["model_version"] = "0.1.0"
    s["region"] = "international"
    s["source_status"] = "llm_draft"
    s["evidence_refs"] = [{"source_type": "llm_pretraining"}]
    s["times_seen"] = 0
    s["last_updated"] = "2026-06-17"

out = Path("data/disciplinary_landscape/seeds/international_seed.jsonl")
existing = out.read_text(encoding="utf-8").splitlines() if out.exists() else []
existing_ids = {json.loads(line)["discipline_id"] for line in existing if line.strip()}
new_lines = [json.dumps(s, ensure_ascii=False) for s in seeds if s["discipline_id"] not in existing_ids]

with out.open("a", encoding="utf-8") as f:
    for line in new_lines:
        f.write(line + "\n")

print(f"Appended {len(new_lines)} new seeds (skipped {len(seeds) - len(new_lines)} existing)")
